apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: reserve
    port: 11880
    targetPort: 11880
  selector:
    k8s-app: {{ .Values.labels }}
