apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app:  {{ .Values.labels }}
  template:
    metadata:
      labels:
        app:  {{ .Values.labels }}
    spec:
      containers:
      - name:  {{.Chart.Name}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.pginfo.passwd }}"
        - name: POSTGRES_DB
          value: "{{ .Values.pginfo.db }}"
        ports:
        - containerPort: 5432
          hostPort: 5432
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname }}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
