apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: {{ .Values.labels }}
