apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ .Values.labels }}
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.labels }}
    spec:
      containers:
      - name:  {{.Chart.Name}}
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - name: sys
          mountPath: /sys
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname }}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
