apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.labels }}
spec:
  ports:
  - port: 10000
  selector:
    k8s-app: {{ .Values.labels }}
