apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{.Chart.Name}}
  namespace: {{ .Values.namespace }}	
spec:
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      containers:
      - name:  {{.Chart.Name}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
          hostPort: 30002
        - containerPort: 30019
          hostPort: 30001 
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeSelector.hostname }}
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
